version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
    logging:
      driver: none
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rserver
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
    volumes:
      - ./output:/output
    environment:
      - RABBITMQ_HOST=rabbitmq
      - LOG_LEVEL=ERROR
      - THREADS=4
    command: sh -c "sleep 10; python main.py"
